using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace projecteuler
{
    class problem2
    {

        // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        //By starting with 1 and 2, the first 10 terms will be:
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    
        public static int GetFiboSum()
        {
            int sum = 2;
            int first = 1;
            int second = 2;

            while (second < 4000000)
            {
                int result = fibo(first, second);
                first = second;
                second = result;
                if(result % 2 == 0)
                    sum += result;
            }

            return sum;
        }

        

        private static  int fibo(int a, int b)
        {
            return a + b;
        }


    }
}
